### ISSUE TITLE
Menu Sections Disappear on Different Pages

### ISSUE THREAD

**Issue by koronkowy** [Lownin/dc541.org#5]
![IImage of Meetings Page](https://i.imgur.com/LUMU9Fe.png)

Occurs on:
https://dsca93pmobtt1.cloudfront.net/meetings.htm
https://dsca93pmobtt1.cloudfront.net/projects.htm

This might be intentional, where you're dropping the full menu links each time you're in a section, but this is pretty unusual for UX on the web in 2019.

There should be a solution for navigation that is populating static-pre-content/markdown and not where you have to individually manage the menu for each static page created.

**Comment by Lownin** [comment]
This issue was with the old site.  It's been fixed in the new Hugo version.
Thanks!
